export const tours = [
  {
    id: "1",
    title: "10-Day Japan Adventure",
    destination: "Japan",
    image: "/images/tours/japan.webp",
    gallery: [],
    duration: 10,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Experience the perfect blend of ancient traditions and modern wonders in Japan. From the bustling streets of Tokyo to the serene temples of Kyoto, this tour offers a comprehensive exploration of Japanese culture, cuisine, and landscapes.",
    highlights: [
      "Explore Tokyo's vibrant neighborhoods and modern attractions",
      "Visit the iconic Mount Fuji and surrounding scenic areas",
      "Experience traditional culture in historic Kyoto",
      "Ride the famous bullet train (Shinkansen)",
      "Participate in a traditional tea ceremony",
      "Stay in a traditional Japanese ryokan",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Tokyo", description: "Arrive at Narita International Airport. Transfer to your hotel in Tokyo. Welcome dinner with the group." },
      { day: 2, title: "Tokyo Exploration", description: "Visit Meiji Shrine, Harajuku, Shibuya Crossing, and Tokyo Tower. Evening free to explore on your own." },
      { day: 3, title: "Tokyo to Mount Fuji", description: "Travel to the Mount Fuji area. Visit the 5th Station (weather permitting) and Lake Kawaguchi. Overnight stay in a traditional ryokan." },
      { day: 4, title: "Mount Fuji to Kyoto", description: "Morning at leisure. Afternoon bullet train to Kyoto. Evening walk through Gion district." },
      { day: 5, title: "Kyoto Temples & Gardens", description: "Visit Kinkaku-ji (Golden Pavilion), Ryoan-ji Zen Garden, and Arashiyama Bamboo Grove." },
      { day: 6, title: "Kyoto Cultural Day", description: "Participate in a traditional tea ceremony and kimono experience. Visit Fushimi Inari Shrine." },
      { day: 7, title: "Kyoto to Hiroshima", description: "Day trip to Hiroshima. Visit Peace Memorial Park and Museum. Ferry to Miyajima Island to see the floating torii gate." },
      { day: 8, title: "Kyoto to Osaka", description: "Travel to Osaka. Visit Osaka Castle and Dotonbori district. Evening food tour." },
      { day: 9, title: "Osaka Free Day", description: "Free day to explore Osaka or take an optional day trip to Nara. Farewell dinner in the evening." },
      { day: 10, title: "Departure", description: "Transfer to Kansai International Airport for your departure flight." },
    ],
    inclusions: [
      "9 nights accommodation (3★ and 4★ hotels, 1 night in traditional ryokan)",
      "Daily breakfast, 3 lunches, and 5 dinners including welcome and farewell dinners",
      "All transportation within Japan including bullet train tickets",
      "English-speaking local guide throughout",
      "All entrance fees to attractions mentioned in the itinerary",
      "Cultural experiences: tea ceremony, kimono wearing",
      "Airport transfers on arrival and departure",
    ],
    exclusions: [
      "International flights to/from Japan",
      "Travel insurance",
      "Meals not mentioned in the inclusions",
      "Personal expenses and souvenirs",
      "Optional activities not mentioned in the itinerary",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "2",
    title: "12-Day Italian Discovery",
    destination: "Italy",
    image: "/images/tours/italy.webp",
    gallery: [],
    duration: 12,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Explore the art, history, and culinary delights of beautiful Italy. From the ancient ruins of Rome to the romantic canals of Venice, this comprehensive tour covers Italy's most iconic destinations.",
    highlights: [
      "Explore the ancient Colosseum and Roman Forum",
      "Visit the Vatican City and Sistine Chapel",
      "Experience Renaissance art in Florence",
      "Romantic gondola ride in Venice",
      "Taste authentic Italian cuisine and wines",
      "Visit the stunning Amalfi Coast",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Rome", description: "Arrive at Rome Fiumicino Airport. Transfer to hotel. Welcome dinner." },
      { day: 2, title: "Ancient Rome", description: "Visit Colosseum, Roman Forum, and Palatine Hill. Afternoon at leisure." },
      { day: 3, title: "Vatican City", description: "Explore Vatican Museums, Sistine Chapel, and St. Peter's Basilica." },
      { day: 4, title: "Rome to Florence", description: "Morning train to Florence. Afternoon walking tour of historic center." },
      { day: 5, title: "Florence Art & Culture", description: "Visit Uffizi Gallery, Duomo, and Ponte Vecchio. Cooking class in evening." },
      { day: 6, title: "Tuscany Day Trip", description: "Visit Siena and San Gimignano. Wine tasting in Chianti region." },
      { day: 7, title: "Florence to Venice", description: "Morning train to Venice. Afternoon exploration of St. Mark's Square." },
      { day: 8, title: "Venice Discovery", description: "Visit Doge's Palace, gondola ride, and glass-making demonstration in Murano." },
      { day: 9, title: "Venice to Amalfi Coast", description: "Travel to Sorrento. Evening at leisure." },
      { day: 10, title: "Amalfi Coast", description: "Visit Positano and Amalfi. Boat trip along the coast." },
      { day: 11, title: "Return to Rome", description: "Morning at leisure. Afternoon return to Rome. Farewell dinner." },
      { day: 12, title: "Departure", description: "Transfer to Rome airport for departure." },
    ],
    inclusions: [
      "11 nights accommodation in 3★ and 4★ hotels",
      "Daily breakfast and 6 dinners",
      "All transportation including high-speed trains",
      "English-speaking local guides",
      "All entrance fees to attractions",
      "Cooking class in Florence",
      "Gondola ride in Venice",
      "Airport transfers",
    ],
    exclusions: [
      "International flights to/from Italy",
      "Travel insurance",
      "Meals not mentioned",
      "Personal expenses",
      "Optional activities",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "3",
    title: "8-Day Turkish Delight",
    destination: "Turkey",
    image: "/images/tours/turkey.webp",
    gallery: [],
    duration: 8,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Discover the crossroads of Europe and Asia in fascinating Turkey. Experience the rich history, stunning landscapes, and warm hospitality of this incredible country.",
    highlights: [
      "Explore the historic Sultanahmet district in Istanbul",
      "Hot air balloon ride over Cappadocia",
      "Visit the ancient city of Ephesus",
      "Relax at Pamukkale's thermal pools",
      "Experience Turkish baths and cuisine",
      "Shop at the Grand Bazaar",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Istanbul", description: "Arrive at Istanbul Airport. Transfer to hotel. Welcome dinner." },
      { day: 2, title: "Istanbul Old City", description: "Visit Blue Mosque, Hagia Sophia, Topkapi Palace, and Grand Bazaar." },
      { day: 3, title: "Istanbul to Cappadocia", description: "Flight to Cappadocia. Explore Goreme Open Air Museum." },
      { day: 4, title: "Cappadocia Adventure", description: "Hot air balloon ride at sunrise. Underground city tour." },
      { day: 5, title: "Cappadocia to Pamukkale", description: "Drive to Pamukkale. Visit the white travertine terraces." },
      { day: 6, title: "Pamukkale to Ephesus", description: "Visit ancient Ephesus and the House of Virgin Mary." },
      { day: 7, title: "Return to Istanbul", description: "Flight back to Istanbul. Bosphorus cruise. Turkish bath experience." },
      { day: 8, title: "Departure", description: "Transfer to airport for departure." },
    ],
    inclusions: [
      "7 nights accommodation in 3★ and 4★ hotels",
      "Daily breakfast and 4 dinners",
      "Domestic flights within Turkey",
      "English-speaking local guides",
      "All entrance fees",
      "Hot air balloon ride",
      "Bosphorus cruise",
      "Airport transfers",
    ],
    exclusions: [
      "International flights to/from Turkey",
      "Travel insurance",
      "Meals not mentioned",
      "Personal expenses",
      "Optional activities",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "4",
    title: "6-Day Kenyan Safari",
    destination: "Kenya",
    image: "/images/tours/kenya/kenya-1.webp",
    gallery: [
      "/images/tours/kenya/kenya-2.webp",
      "/images/tours/kenya/kenya-3.webp",
      "/images/tours/kenya/kenya-4.webp",
      "/images/tours/kenya/kenya-5.webp",
      "/images/tours/kenya/kenya-6.webp",
      "/images/tours/kenya/kenya-7.webp",
      "/images/tours/kenya/kenya-8.webp",
      "/images/tours/kenya/kenya-9.webp",
      "/images/tours/kenya/kenya-10.webp",
    ],
    duration: 6,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Explore Kenya like never before with our 6-day all-inclusive group tour covering Nairobi, Masai Mara, Naivasha & Hell’s Gate, guided by a Kannada tour manager. Enjoy luxury stays, thrilling safaris, and rich cultural experiences—all with Indian meals and seamless travel arrangements.",
    highlights: [
      "Nairobi city tour with shopping at the vibrant Masai Market.",
      "Thrilling game drives in Masai Mara National Reserve.",
      "Cultural visit to the traditional Masai Tribes village.",
      "Scenic boat safari on Lake Naivasha with hippo sightings.",
      "Unique walking and cycling experience at Hell's Gate National Park.",
      "Travel in luxury 4x4 Land Cruisers with a dedicated Kannada tour manager.",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Nairobi – Warm Welcome and Relaxation",
        description:
          "Upon your arrival at Nairobi Airport in the evening, the Flying Passport team will greet you and escort you to your 4-star hotel, Long View Suites. After check-in, enjoy a warm welcome with coffee and snacks. Later, relish a specially prepared Indian dinner. Unwind with a campfire, music, and dance as you begin your exciting Kenyan adventure.\n\nMeals: Indian Breakfast, Lunch & Dinner\nAccommodation: Long View Suites, Nairobi",
      },
      {
        day: 2,
        title: "Nairobi City Tour & Masai Market Experience",
        description:
          "After a delicious Indian breakfast, begin your day with a 3-hour Nairobi city tour, discovering the highlights of the capital. Enjoy lunch at an Indian restaurant, followed by a visit to the vibrant Masai Market for a unique shopping experience. Return to the hotel for a comforting Indian dinner and a restful night.\n\nMeals: Indian Breakfast, Lunch & Dinner\nAccommodation: Long View Suites, Nairobi",
      },
      {
        day: 3,
        title: "Nairobi to Masai Mara – Tribal Visit & Scenic Drive",
        description:
          "After breakfast, embark on a scenic journey in a luxurious 4x4 Land Cruiser to Masai Mara, driving along the breathtaking Great Rift Valley. Pause at a viewpoint for panoramic views. On arrival, enjoy a picnic lunch, then visit an authentic Masai tribal village to experience their culture and traditions. Check-in at Jambo Mara Safari Lodge or Masai Mara Sopa Lodge for dinner and overnight stay.\n\nMeals: Breakfast, Lunch & Dinner\nAccommodation: Jambo Mara Safari Lodge or Masai Mara Sopa Lodge",
      },
      {
        day: 4,
        title: "Full-Day Safari in Masai Mara",
        description:
          "Start early with breakfast, then head into Masai Mara Reserve for a full day of game viewing. Spot Africa’s Big Five, witness the Great Migration (seasonal), and enjoy a picnic lunch at Hippo Pool. Capture the stunning wildlife and landscapes during morning and afternoon game drives. Return in the evening to the lodge for dinner and rest.\n\nMeals: Breakfast, Lunch & Dinner\nAccommodation: Jambo Mara Safari Lodge or Masai Mara Sopa Lodge",
      },
      {
        day: 5,
        title: "Masai Mara to Naivasha – Boat Safari Adventure",
        description:
          "After breakfast, drive about 4 hours to Naivasha National Park. After a refreshing lunch, embark on a serene boat ride safari on Lake Naivasha, known for its birdlife and hippo sightings. Enjoy a peaceful evening and dinner at the beautiful Chambai Safari Hotel.\n\nMeals: Breakfast, Lunch & Dinner\nAccommodation: Chambai Safari Hotel, Naivasha",
      },
      {
        day: 6,
        title: "Hell's Gate National Park & Departure",
        description:
          "After an early breakfast, visit Hell’s Gate National Park for an exciting walking or cycling safari, and explore the Olkaria Geothermal Power Plant and natural hot springs. After the adventure, enjoy a picnic lunch during the return drive to Nairobi. Guests with evening flights will be dropped off at Nairobi Airport for the return journey.\n\nMeals: Breakfast, Lunch",
      },
    ],
    inclusions: [
      "Economy class return flight tickets (Bangalore – Nairobi – Bangalore)",
      "Accommodation in 4-star hotels (2 nights Nairobi, 2 nights Masai Mara, 1 night Naivasha)",
      "Daily Indian meals: Breakfast, Lunch & Dinner",
      "Luxury 4x4 Land Cruiser for all transfers and safaris",
      "All sightseeing and national park entry tickets as per itinerary",
      "Boat ride safari on Lake Naivasha",
      "Guided walking/cycling experience at Hell's Gate National Park",
      "Visit to Masai tribal village",
      "Free travel insurance (below 60 years)",
      "Kenya tourist visa for all travelers",
      "Services of an experienced Kannada-speaking tour manager throughout the trip",
    ],
    exclusions: [
      "5% GST & 5% TCS (as applicable for international travel)",
      "Tips for driver and guide (USD 5 per day per person, total USD 25 per person)",
      "Personal expenses: laundry, porterage, telephone, minibar, drinks not part of the regular menu",
      "Meals not mentioned in the itinerary",
      "Additional excursions or entrance fees not specified in the itinerary",
      "Cost for any individual sightseeing or activity not part of the group tour",
      "Travel insurance charges for travelers above 60 years (if applicable)",
      "Any other item not mentioned under “What’s Included”",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "5",
    title: "9-Day Thailand Explorer",
    destination: "Thailand",
    image: "/images/tours/thailand.webp",
    gallery: [],
    duration: 9,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Experience the vibrant culture and stunning beaches of Thailand. From bustling Bangkok to tropical islands, discover the Land of Smiles.",
    highlights: [
      "Explore the vibrant streets of Bangkok",
      "Visit ancient temples and palaces",
      "Experience traditional Thai culture in Chiang Mai",
      "Relax on pristine beaches in Phuket",
      "Island hopping to Phi Phi Islands",
      "Enjoy authentic Thai cuisine and cooking classes",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Bangkok", description: "Arrive at Bangkok airport. Transfer to hotel. Welcome dinner." },
      { day: 2, title: "Bangkok Temples", description: "Visit Wat Pho, Wat Arun, and Grand Palace. Evening tuk-tuk tour." },
      { day: 3, title: "Bangkok to Chiang Mai", description: "Flight to Chiang Mai. Visit local markets and temples." },
      { day: 4, title: "Chiang Mai Culture", description: "Elephant sanctuary visit. Traditional cooking class." },
      { day: 5, title: "Chiang Mai to Phuket", description: "Flight to Phuket. Beach time and relaxation." },
      { day: 6, title: "Phi Phi Islands", description: "Full day island hopping tour to Phi Phi Islands." },
      { day: 7, title: "Phuket Beach Day", description: "Free day at the beach. Optional water activities." },
      { day: 8, title: "Phuket to Bangkok", description: "Flight back to Bangkok. Last-minute shopping. Farewell dinner." },
      { day: 9, title: "Departure", description: "Transfer to airport for departure." },
    ],
    inclusions: [
      "8 nights accommodation in 3★ and 4★ hotels",
      "Daily breakfast and 5 dinners",
      "Domestic flights within Thailand",
      "English-speaking local guides",
      "All entrance fees",
      "Cooking class",
      "Island hopping tour",
      "Airport transfers",
    ],
    exclusions: [
      "International flights to/from Thailand",
      "Travel insurance",
      "Meals not mentioned",
      "Personal expenses",
      "Optional activities",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "6",
    title: "13-Day European Highlights",
    destination: "Europe",
    image: "/images/tours/europe/europe-group-tour-1.webp",
    gallery: [
      "/images/tours/europe/europe-group-tour-2.webp",
      "/images/tours/europe/europe-group-tour-3.webp",
      "/images/tours/europe/europe-group-tour-4.webp",
      "/images/tours/europe/europe-group-tour-5.webp",
      "/images/tours/europe/europe-group-tour-6.webp",
      "/images/tours/europe/europe-group-tour-7.webp",
      "/images/tours/europe/europe-group-tour-8.webp",
      "/images/tours/europe/europe-group-tour-9.webp",
      "/images/tours/europe/europe-group-tour-10.webp",
    ],
    duration: 13,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Explore 8 iconic European countries in 13 unforgettable days with our guided group tour, covering Paris, Venice, Swiss Alps, and more. Enjoy Indian meals, 4-star stays, and seamless travel with flights, visas, and sightseeing included.",
    highlights: [
      "Visit iconic landmarks like the Eiffel Tower, Leaning Tower of Pisa, and Cologne Cathedral.",
      "Enjoy a scenic Seine River cruise and Mt. Titlis cable car experience.",
      "Explore charming cities including Paris, Amsterdam, Interlaken, and Venice.",
      "Witness Europe's natural beauty at Rhine Falls and the Swiss Alps.",
      "Discover cultural gems like Bern, Innsbruck, and Milan.",
      "Stay in handpicked 3–4 star hotels with Indian meals and guided tours throughout.",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Paris",
        description:
          "Arrive in the iconic city of Paris. Upon arrival, meet our representative who will assist with hotel transfers. Check in, relax, and unwind after your flight. In the evening, enjoy a specially arranged packed Indian dinner to ease into your European adventure.\nMeals: Dinner",
      },
      {
        day: 2,
        title: "Paris City Tour",
        description:
          "After breakfast, start the day with an orientation tour of Paris. Visit landmarks like the Champs-Élysées and Arc de Triomphe. Ascend the Eiffel Tower up to Level 2 for panoramic city views. Later, enjoy a scenic Seine River cruise, gliding past iconic Parisian architecture. Return to the hotel for dinner and overnight stay.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 3,
        title: "Belgium (Brussels)",
        description:
          "Depart Paris and drive to Brussels, the capital of Belgium. Enjoy an orientation tour including the Grand Place, Manneken Pis, and a photo stop at the Atomium. Later, continue into the Netherlands for dinner and overnight stay.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 4,
        title: "Netherlands (Countryside & Amsterdam)",
        description:
          "Explore the beautiful Dutch countryside. Visit a traditional windmill, a wooden shoe (clog) factory, and a local cheese farm for demonstrations and tastings. Spend free time at Amsterdam’s central square. Dinner and overnight in the Netherlands.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 5,
        title: "Cologne, Germany",
        description:
          "Travel into Germany and visit Cologne. Tour the grand Cologne Cathedral (UNESCO site) and enjoy leisure time in the vibrant Old Town along the Rhine River. Proceed to your hotel in Germany for dinner and overnight stay.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 6,
        title: "Rhine Falls & Arrival in Switzerland",
        description:
          "Start your day in Germany’s Black Forest and visit a cuckoo clock workshop. Head to the Rhine Falls – Europe’s largest waterfall – and enjoy a thrilling boat ride. Continue to Zurich, Switzerland, for an orientation tour and then check into your hotel.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 7,
        title: "Mt. Titlis & Lucerne",
        description:
          "Enjoy a full-day excursion to Mt. Titlis via cable car and rotating gondola. Explore the glacier cave, the famous Cliff Walk, and snow-covered peaks (Ice Flyer not included). Later, visit Lucerne to see the Lion Monument and Chapel Bridge. Return to the hotel for dinner.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 8,
        title: "Bern & Interlaken",
        description:
          "Visit the Lindt Chocolate Museum in the morning for a sweet start. Then explore Bern’s medieval Old Town and famous Zytglogge clock tower. Continue to Interlaken for shopping and photo opportunities amid breathtaking alpine scenery. Return to your hotel in Switzerland for dinner.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 9,
        title: "Liechtenstein & Austria (Innsbruck)",
        description:
          "Begin with a visit to Vaduz, the capital of Liechtenstein. Proceed to Innsbruck, Austria, for an orientation tour of its historic old town and Golden Roof. End the day with a visit to the Swarovski Crystal Showroom. Overnight in Austria.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 10,
        title: "Venice, Italy",
        description:
          "Travel to Venice, the magical city of canals. Ride a Vaporetto (water taxi) to St. Mark's Square. Take a guided walking tour including views of St. Mark’s Basilica, Doge’s Palace, Bell Tower, and Bridge of Sighs. Free time for shopping and exploring. Dinner and overnight stay in the Padova area.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 11,
        title: "Pisa & Milan",
        description:
          "Head to Pisa to visit the Field of Miracles featuring the Leaning Tower, Cathedral, and Baptistery. Then proceed to Milan. Upon arrival, check in to your hotel, have dinner, and rest.\nMeals: Breakfast, Lunch, Dinner",
      },
      {
        day: 12,
        title: "Milan City Tour & Departure",
        description:
          "Begin with an orientation tour of Milan. Visit the Duomo Cathedral (outside) and stroll through Galleria Vittorio Emanuele II. Enjoy some free time before lunch. Later, transfer to Milan MXP Airport for your return flight.\nMeals: Breakfast, Lunch",
      },
      {
        day: 13,
        title: "Transit in Muscat & Return to Bangalore",
        description:
          "Fly from Milan to Muscat with a layover before your final flight to Bangalore. Relax at the airport lounge, shop duty-free, or grab a quick bite during transit.\nMeals: As per flight service",
      },
    ],
    inclusions: [
      "Economy class return flight tickets (Bangalore ⇌ Europe via Muscat)",
      "Visa fees for all countries visited",
      "Travel insurance for all passengers (below 60 years)",
      "Accommodation in 3-star or 4-star hotels throughout the tour",
      "Daily Indian breakfast, lunch, and dinner",
      "Deluxe air-conditioned motor coach for all internal travel",
      "Services of an experienced Tour Manager throughout the tour",
      "Guided sightseeing and orientation tours in:",
      "France, Belgium, Netherlands, Germany, Switzerland, Liechtenstein, Austria, and Italy",
      "Major attractions and experiences:",
      "Eiffel Tower (Level 2), Seine River Cruise, Rhine Falls Boat Ride, Mt. Titlis Cable Car & Cliff Walk, Lucerne, Interlaken, Pisa Leaning Tower, Venice Vaporetto Ride, Swarovski Crystal World, Chocolate Museum visit",
      "All hotel transfers and airport pick-up/drop",
      "2-night stay in Paris",
      "2-night stay in the Netherlands",
      "1-night stay in Germany",
      "3-night stay in Switzerland",
      "1-night stay in Austria",
      "2-night stay in Italy",
    ],
    exclusions: [
      "Personal expenses such as:",
      "Laundry, minibar, telephone calls, room service, drinks not part of group meals",
      "Tips for driver, guide, and tour manager (approx. €5 per person per day)",
      "Any meals or beverages not mentioned in the itinerary",
      "Optional excursions, entrance fees, or city sightseeing not specified in the inclusions",
      "Any cost arising due to flight delays, natural calamities, or unforeseen situations",
      "5% GST (Goods & Services Tax) – mandatory & not included in the price",
      "5% TCS (Tax Collected at Source) – mandatory & not included in the price",
      "Expenses incurred for RT-PCR or COVID-related testing (if required at the time of travel)",
      "Additional charges for excess baggage or seat selection on flights",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "7",
    title: "10-Day Vietnam Journey",
    destination: "Vietnam",
    image: "/images/tours/vietnam.webp",
    gallery: [],
    duration: 10,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Explore the rich history and natural beauty of Vietnam. From the bustling streets of Ho Chi Minh City to the stunning landscapes of Ha Long Bay.",
    highlights: [
      "Explore the historic streets of Hanoi",
      "Cruise through Ha Long Bay's limestone karsts",
      "Discover the ancient town of Hoi An",
      "Experience the vibrant energy of Ho Chi Minh City",
      "Visit the Cu Chi Tunnels",
      "Enjoy authentic Vietnamese cuisine",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Hanoi", description: "Arrive in Hanoi. Transfer to hotel. Welcome dinner." },
      { day: 2, title: "Hanoi City Tour", description: "Visit Ho Chi Minh Mausoleum, Temple of Literature, and Old Quarter." },
      { day: 3, title: "Hanoi to Ha Long Bay", description: "Drive to Ha Long Bay. Overnight cruise with dinner on board." },
      { day: 4, title: "Ha Long Bay to Hoi An", description: "Morning in Ha Long Bay. Flight to Da Nang, transfer to Hoi An." },
      { day: 5, title: "Hoi An Ancient Town", description: "Walking tour of Hoi An. Lantern festival in the evening." },
      { day: 6, title: "Hoi An to Ho Chi Minh City", description: "Flight to Ho Chi Minh City. City orientation tour." },
      { day: 7, title: "Cu Chi Tunnels", description: "Visit Cu Chi Tunnels. Afternoon at leisure in the city." },
      { day: 8, title: "Mekong Delta", description: "Day trip to Mekong Delta. Boat rides and local experiences." },
      { day: 9, title: "Ho Chi Minh City", description: "Free day for shopping and exploration. Farewell dinner." },
      { day: 10, title: "Departure", description: "Transfer to airport for departure." },
    ],
    inclusions: [
      "9 nights accommodation including 1 night on Ha Long Bay cruise",
      "Daily breakfast and 6 dinners",
      "Domestic flights within Vietnam",
      "English-speaking local guides",
      "All entrance fees",
      "Ha Long Bay cruise",
      "Mekong Delta tour",
      "Airport transfers",
    ],
    exclusions: [
      "International flights to/from Vietnam",
      "Travel insurance",
      "Meals not mentioned",
      "Personal expenses",
      "Optional activities",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "8",
    title: "11-Day Greek Island Hopping",
    destination: "Greece",
    image: "/images/tours/greek.webp",
    gallery: [],
    duration: 11,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Discover the stunning islands and ancient history of Greece. From the iconic white buildings of Santorini to the vibrant nightlife of Mykonos.",
    highlights: [
      "Explore ancient Athens and the Acropolis",
      "Sunset views in Santorini",
      "Beach time and nightlife in Mykonos",
      "Discover the Palace of Knossos in Crete",
      "Traditional Greek cuisine and wine tasting",
      "Island hopping by ferry",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Athens", description: "Arrive in Athens. Transfer to hotel. Welcome dinner." },
      { day: 2, title: "Athens Sightseeing", description: "Visit Acropolis, Parthenon, and Ancient Agora. Afternoon at leisure." },
      { day: 3, title: "Athens to Mykonos", description: "Ferry to Mykonos. Explore Mykonos Town and beaches." },
      { day: 4, title: "Mykonos Island", description: "Beach day and optional visit to nearby Delos island." },
      { day: 5, title: "Mykonos to Santorini", description: "Ferry to Santorini. Explore Fira and famous sunset in Oia." },
      { day: 6, title: "Santorini Exploration", description: "Wine tasting tour and visit to Akrotiri archaeological site." },
      { day: 7, title: "Santorini to Crete", description: "Ferry to Crete. Explore Heraklion and visit Knossos Palace." },
      { day: 8, title: "Crete Discovery", description: "Visit traditional villages and enjoy Cretan cuisine." },
      { day: 9, title: "Crete to Athens", description: "Flight back to Athens. Last-minute shopping and sightseeing." },
      { day: 10, title: "Athens Free Day", description: "Free day in Athens. Optional day trip or museum visits." },
      { day: 11, title: "Departure", description: "Transfer to airport for departure." },
    ],
    inclusions: [
      "10 nights accommodation in 3★ and 4★ hotels",
      "Daily breakfast and 5 dinners",
      "Inter-island ferries and domestic flight",
      "English-speaking local guides",
      "All entrance fees",
      "Wine tasting in Santorini",
      "Airport and port transfers",
    ],
    exclusions: [
      "International flights to/from Greece",
      "Travel insurance",
      "Meals not mentioned",
      "Personal expenses",
      "Optional activities",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "9",
    title: "8-Day Moroccan Adventure",
    destination: "Morocco",
    image: "/images/tours/morocco.webp",
    gallery: [],
    duration: 8,
    groupSize: "40",
    price: 0,
    status: "expired",
    departureDate: "Dates will be announced soon",
    description:
      "Experience the colors, flavors, and landscapes of magical Morocco. From bustling souks to the Sahara Desert, discover the beauty of North Africa.",
    highlights: [
      "Explore the vibrant souks of Marrakech",
      "Visit the blue city of Chefchaouen",
      "Experience the imperial city of Fes",
      "Camel trekking in the Sahara Desert",
      "Overnight in desert camp under the stars",
      "Traditional Moroccan cuisine and mint tea",
    ],
    itinerary: [
      { day: 1, title: "Arrival in Casablanca", description: "Arrive in Casablanca. Visit Hassan II Mosque. Transfer to Rabat." },
      { day: 2, title: "Rabat to Chefchaouen", description: "Explore Rabat's medina. Drive to the blue city of Chefchaouen." },
      { day: 3, title: "Chefchaouen to Fes", description: "Morning in Chefchaouen. Afternoon drive to Fes." },
      { day: 4, title: "Fes Exploration", description: "Full day exploring Fes medina, tanneries, and madrasas." },
      { day: 5, title: "Fes to Sahara Desert", description: "Drive through Middle Atlas to Merzouga. Camel trek to desert camp." },
      { day: 6, title: "Sahara to Ouarzazate", description: "Sunrise in desert. Drive to Ouarzazate via Todra Gorge." },
      { day: 7, title: "Ouarzazate to Marrakech", description: "Visit Ait Benhaddou kasbah. Drive to Marrakech over Atlas Mountains." },
      { day: 8, title: "Marrakech & Departure", description: "Explore Marrakech medina and Jemaa el-Fnaa square. Transfer to airport." },
    ],
    inclusions: [
      "7 nights accommodation including 1 night in desert camp",
      "Daily breakfast and 4 dinners",
      "Private transportation throughout",
      "English-speaking local guide",
      "All entrance fees",
      "Camel trekking experience",
      "Airport transfers",
    ],
    exclusions: [
      "International flights to/from Morocco",
      "Travel insurance",
      "Meals not mentioned",
      "Personal expenses",
      "Optional activities",
    ],
    singleOccupancy: 0,
    childPrice: 0,
  },
  {
    id: "10",
    title: "9-Day China Discovery",
    destination: "China",
    image: "/images/tours/China/China_1.png",
    gallery: [
      "/images/tours/China/China_2.png",
      "/images/tours/China/China_3.png",
      "/images/tours/China/China_4.png",
      "/images/tours/China/China_5.png",
      "/images/tours/China/China_6.png",
      "/images/tours/China/China_7.png",
      "/images/tours/China/China_8.png",
      "/images/tours/China/China_9.png",
    ],
    duration: 9,
    groupSize: "40",
    price: 285000,
    status: "upcoming",
    departureDate: "October 27, 2025",
    description:
      "Explore China’s rich history and modern marvels, from the Great Wall to vibrant Shanghai, on this immersive 9-day group tour. Enjoy cultural experiences, iconic landmarks, and Indian meals with seamless travel arrangements.",
    highlights: [
      "Walk along the iconic Great Wall of China",
      "Explore the historic Forbidden City in Beijing",
      "Visit the Terracotta Warriors in Xi’an",
      "Cruise the vibrant Huangpu River in Shanghai",
      "Experience the scenic beauty of Guilin’s Li River",
      "Savor authentic Chinese cuisine with Indian meal options",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Beijing",
        description:
          "Arrive at Beijing Capital International Airport on October 27. Meet our representative and transfer to a 4-star hotel. Enjoy a welcome Indian dinner and relax after your journey.\n\nMeals: Dinner\nAccommodation: 4-star hotel, Beijing",
      },
      {
        day: 2,
        title: "Beijing – Forbidden City & Tiananmen Square",
        description:
          "After breakfast, visit Tiananmen Square and the Forbidden City, the imperial palace complex. Enjoy an Indian lunch, followed by a visit to the Temple of Heaven. Evening at leisure with Indian dinner.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Beijing",
      },
      {
        day: 3,
        title: "Great Wall of China",
        description:
          "Travel to the Mutianyu section of the Great Wall. Enjoy a cable car ride and time to explore this iconic landmark. Return to Beijing for an Indian dinner and rest.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Beijing",
      },
      {
        day: 4,
        title: "Beijing to Xi’an",
        description:
          "Morning high-speed train to Xi’an. After an Indian lunch, visit the ancient Xi’an City Wall. Evening free to explore the Muslim Quarter with dinner at an Indian restaurant.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Xi’an",
      },
      {
        day: 5,
        title: "Xi’an – Terracotta Warriors",
        description:
          "Visit the world-famous Terracotta Warriors and Horses Museum. After lunch, explore the Big Wild Goose Pagoda. Enjoy an Indian dinner and a cultural show in the evening.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Xi’an",
      },
      {
        day: 6,
        title: "Xi’an to Guilin",
        description:
          "Fly to Guilin, known for its dramatic limestone karsts. After an Indian lunch, visit Reed Flute Cave. Evening at leisure with dinner at the hotel.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Guilin",
      },
      {
        day: 7,
        title: "Guilin – Li River Cruise",
        description:
          "Enjoy a scenic Li River cruise to Yangshuo, surrounded by lush mountains. Explore Yangshuo’s West Street in the afternoon. Return to Guilin for an Indian dinner.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Guilin",
      },
      {
        day: 8,
        title: "Guilin to Shanghai",
        description:
          "Fly to Shanghai. After an Indian lunch, explore the Bund and Nanjing Road. Evening Huangpu River cruise followed by an Indian dinner.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Shanghai",
      },
      {
        day: 9,
        title: "Shanghai & Departure",
        description:
          "Visit Yu Garden and the Old Town in the morning. After an Indian lunch, transfer to Shanghai Pudong International Airport for your return flight. Bid farewell to an unforgettable China adventure.\n\nMeals: Breakfast, Lunch\nAccommodation: None",
      },
    ],
    inclusions: [
      "Economy class return flight tickets (Bangalore – China – Bangalore)",
      "Accommodation in 4-star hotels (3 nights Beijing, 2 nights Xi’an, 2 nights Guilin, 1 night Shanghai)",
      "Daily Indian breakfast, lunch, and dinner (as specified in itinerary)",
      "High-speed train tickets (Beijing to Xi’an)",
      "Domestic flights (Xi’an to Guilin, Guilin to Shanghai)",
      "All sightseeing and entrance fees as per itinerary",
      "Li River cruise and Huangpu River cruise",
      "Services of an English-speaking tour manager throughout",
      "China tourist visa for all travelers",
      "Free travel insurance (below 60 years)",
      "All airport and hotel transfers",
    ],
    exclusions: [
      "5% GST & 5% TCS (as applicable for international travel)",
      "Tips for driver and guide (USD 5 per day per person, total USD 45 per person)",
      "Personal expenses: laundry, porterage, telephone, minibar, drinks not part of the regular menu",
      "Meals not mentioned in the itinerary",
      "Optional excursions or entrance fees not specified in the itinerary",
      "Travel insurance charges for travelers above 60 years (if applicable)",
      "Any other item not mentioned under “What’s Included”",
    ],
    singleOccupancy: 325000,
    childPrice: 245000,
  },
  {
    id: "11",
    title: "10-Day Japan, South Korea & North Korea",
    destination: "Japan, South Korea, North Korea",
    image: "/images/tours/Japan S&N/japan-s-n-01.png",
    gallery: [
      "/images/tours/Japan S&N/japan-s-n-02.png",
      "/images/tours/Japan S&N/japan-s-n-03.png",
      "/images/tours/Japan S&N/japan-s-n-04.png",
      "/images/tours/Japan S&N/japan-s-n-05.png",
      "/images/tours/Japan S&N/japan-s-n-06.png",
      "/images/tours/Japan S&N/japan-s-n-07.png",
      "/images/tours/Japan S&N/japan-s-n-08.png",
      "/images/tours/Japan S&N/japan-s-n-09.png",
      "/images/tours/Japan S&N/japan-s-n-10.png",
    ],
    pdf: "/images/FLYING PASSPORTS JAPAN AND SOUTH KOREA & NORTH KOREA ITINERARY 2025.pdf", // PDF path is correct
    duration: 10,
    groupSize: "40",
    price: 337000,
    status: "upcoming",
    departureDate: "November 7, 2025", // Correct departure date
    description:
      "Embark on an extraordinary 10-day journey through Japan, South Korea, and North Korea, exploring a unique blend of ancient traditions, modern metropolises, and exclusive cultural insights. Enjoy guided tours, Indian meals, and seamless travel arrangements.",
    highlights: [
      "Discover Tokyo’s vibrant cityscape and historic sites",
      "Explore Seoul’s palaces and bustling markets",
      "Experience a rare visit to Pyongyang’s landmarks",
      "Visit Kyoto’s serene temples and gardens",
      "Enjoy a cultural performance in Seoul",
      "Savor regional cuisines with Indian meal options",
    ],
    itinerary: [
      {
        day: 1,
        title: "Arrival in Tokyo, Japan",
        description:
          "Arrive at Tokyo Narita International Airport on November 7. Meet our representative and transfer to a 4-star hotel. Enjoy a welcome Indian dinner and relax.\n\nMeals: Dinner\nAccommodation: 4-star hotel, Tokyo",
      },
      {
        day: 2,
        title: "Tokyo City Tour",
        description:
          "After breakfast, explore Tokyo’s highlights, including Meiji Shrine, Shibuya Crossing, and Asakusa Temple. Enjoy an Indian lunch and free time in the evening. Indian dinner at the hotel.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Tokyo",
      },
      {
        day: 3,
        title: "Tokyo to Kyoto",
        description:
          "Take a bullet train to Kyoto. Visit Kinkaku-ji (Golden Pavilion) and Arashiyama Bamboo Grove after an Indian lunch. Evening at leisure with Indian dinner.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Kyoto",
      },
      {
        day: 4,
        title: "Kyoto Cultural Day",
        description:
          "Explore Fushimi Inari Shrine and participate in a traditional tea ceremony. Indian lunch and dinner included. Evening free to explore Gion district.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Kyoto",
      },
      {
        day: 5,
        title: "Kyoto to Seoul, South Korea",
        description:
          "Fly to Seoul, South Korea. After an Indian lunch, visit Gyeongbokgung Palace and Bukchon Hanok Village. Indian dinner and overnight stay.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Seoul",
      },
      {
        day: 6,
        title: "Seoul Exploration",
        description:
          "Visit N Seoul Tower and Myeongdong Market after breakfast. Enjoy a cultural performance in the evening. Indian lunch and dinner included.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Seoul",
      },
      {
        day: 7,
        title: "Seoul to Pyongyang, North Korea",
        description:
          "Fly to Pyongyang, North Korea. After an Indian lunch, visit the Kumsusan Palace of the Sun and the Arch of Triumph. Indian dinner and overnight stay.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Pyongyang",
      },
      {
        day: 8,
        title: "Pyongyang Highlights",
        description:
          "Explore the Juche Tower and Mansudae Grand Monument. Indian lunch and dinner included. Evening at leisure to experience Pyongyang’s unique atmosphere.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Pyongyang",
      },
      {
        day: 9,
        title: "Pyongyang to Seoul",
        description:
          "Return flight to Seoul. Enjoy a free day for shopping or optional activities in Seoul. Indian lunch and farewell dinner at the hotel.\n\nMeals: Breakfast, Lunch, Dinner\nAccommodation: 4-star hotel, Seoul",
      },
      {
        day: 10,
        title: "Seoul & Departure",
        description:
          "After breakfast, transfer to Incheon International Airport for your return flight. Bid farewell to an unforgettable adventure.\n\nMeals: Breakfast\nAccommodation: None",
      },
    ],
    inclusions: [
      "Economy class return flight tickets (Bangalore – Japan/South Korea/North Korea – Bangalore)",
      "Accommodation in 4-star hotels (2 nights Tokyo, 2 nights Kyoto, 3 nights Seoul, 2 nights Pyongyang)",
      "Daily Indian breakfast, lunch, and dinner (as specified in itinerary)",
      "Domestic flights (Tokyo to Seoul, Seoul to Pyongyang, Pyongyang to Seoul)",
      "Bullet train tickets (Tokyo to Kyoto)",
      "All sightseeing and entrance fees as per itinerary",
      "Cultural experiences: tea ceremony in Kyoto, cultural performance in Seoul",
      "Services of an English-speaking tour manager throughout",
      "Tourist visas for Japan, South Korea, and North Korea for all travelers",
      "Free travel insurance (below 60 years)",
      "All airport and hotel transfers",
    ],
    exclusions: [
      "5% GST & 5% TCS (as applicable for international travel)",
      "Tips for driver and guide (USD 5 per day per person, total USD 50 per person)",
      "Personal expenses: laundry, porterage, telephone, minibar, drinks not part of the regular menu",
      "Meals not mentioned in the itinerary",
      "Optional excursions or entrance fees not specified in the itinerary",
      "Travel insurance charges for travelers above 60 years (if applicable)",
      "Any other item not mentioned under “What’s Included”",
    ],
    singleOccupancy: 389000,
    childPrice: 325000,
  },
];