export const mockAllFormData = {
  contacts: [
    {
      id: "1",
      name: "John Smith",
      email: "john@example.com",
      subject: "Group Tour Inquiry",
      message: "Interested in group tours",
      date: "2024-12-15",
      formType: "Contact",
    },
    {
      id: "2",
      name: "Sarah Johnson",
      email: "sarah@example.com",
      subject: "Custom Package Question",
      message: "Looking for custom packages",
      date: "2024-12-14",
      formType: "Contact",
    },
    {
      id: "3",
      name: "Michael Brown",
      email: "michael@example.com",
      subject: "Corporate Event",
      message: "Organizing corporate event",
      date: "2024-12-13",
      formType: "Contact",
    },
    {
      id: "4",
      name: "Emma Davis",
      email: "emma@example.com",
      subject: "General Inquiry",
      message: "Need more information",
      date: "2024-12-12",
      formType: "Contact",
    },
    {
      id: "5",
      name: "David Wilson",
      email: "david@example.com",
      subject: "Honeymoon Package",
      message: "Planning honeymoon",
      date: "2024-12-11",
      formType: "Contact",
    },
    {
      id: "6",
      name: "Lisa Anderson",
      email: "lisa@example.com",
      subject: "Adventure Tours",
      message: "Interested in adventure",
      date: "2024-12-10",
      formType: "Contact",
    },
    {
      id: "7",
      name: "Robert Taylor",
      email: "robert@example.com",
      subject: "Budget Tours",
      message: "Looking for budget options",
      date: "2024-12-09",
      formType: "Contact",
    },
    {
      id: "8",
      name: "Jennifer Martin",
      email: "jennifer@example.com",
      subject: "Tour Dates",
      message: "When are next tours?",
      date: "2024-12-08",
      formType: "Contact",
    },
  ],
  earlyAccess: [
    { id: "1", name: "Alex Thompson", email: "alex@example.com", date: "2024-12-15", formType: "Early Access" },
    { id: "2", name: "Maria Garcia", email: "maria@example.com", date: "2024-12-14", formType: "Early Access" },
    { id: "3", name: "James Chen", email: "james@example.com", date: "2024-12-13", formType: "Early Access" },
    { id: "4", name: "Patricia Lee", email: "patricia@example.com", date: "2024-12-12", formType: "Early Access" },
    {
      id: "5",
      name: "Christopher Hall",
      email: "christopher@example.com",
      date: "2024-12-11",
      formType: "Early Access",
    },
    { id: "6", name: "Nancy White", email: "nancy@example.com", date: "2024-12-10", formType: "Early Access" },
  ],
  tourBookings: [
    {
      id: "1",
      name: "Kevin Rodriguez",
      email: "kevin@example.com",
      destination: "Paris",
      date: "2024-12-15",
      travelers: 4,
      formType: "Tour Booking",
    },
    {
      id: "2",
      name: "Amanda Clark",
      email: "amanda@example.com",
      destination: "Tokyo",
      date: "2024-12-14",
      travelers: 2,
      formType: "Tour Booking",
    },
    {
      id: "3",
      name: "Ryan Lewis",
      email: "ryan@example.com",
      destination: "Dubai",
      date: "2024-12-13",
      travelers: 5,
      formType: "Tour Booking",
    },
    {
      id: "4",
      name: "Nicole Walker",
      email: "nicole@example.com",
      destination: "London",
      date: "2024-12-12",
      travelers: 3,
      formType: "Tour Booking",
    },
    {
      id: "5",
      name: "Brandon Young",
      email: "brandon@example.com",
      destination: "Singapore",
      date: "2024-12-11",
      travelers: 2,
      formType: "Tour Booking",
    },
    {
      id: "6",
      name: "Stephanie King",
      email: "stephanie@example.com",
      destination: "Barcelona",
      date: "2024-12-10",
      travelers: 4,
      formType: "Tour Booking",
    },
    {
      id: "7",
      name: "Justin Wright",
      email: "justin@example.com",
      destination: "Bali",
      date: "2024-12-09",
      travelers: 6,
      formType: "Tour Booking",
    },
    {
      id: "8",
      name: "Sophie Turner",
      email: "sophie@example.com",
      destination: "Paris",
      date: "2024-12-08",
      travelers: 2,
      formType: "Tour Booking",
    },
    {
      id: "9",
      name: "Tom Harrison",
      email: "tom@example.com",
      destination: "Tokyo",
      date: "2024-12-07",
      travelers: 3,
      formType: "Tour Booking",
    },
    {
      id: "10",
      name: "Emma Wilson",
      email: "emma.w@example.com",
      destination: "Dubai",
      date: "2024-12-06",
      travelers: 5,
      formType: "Tour Booking",
    },
  ],
  homepageEnquiries: [
    {
      id: "1",
      name: "Megan Scott",
      email: "megan@example.com",
      enquiry: "Discounts available?",
      date: "2024-12-15",
      formType: "Homepage Enquiry",
    },
    {
      id: "2",
      name: "Daniel Green",
      email: "daniel@example.com",
      enquiry: "Visa assistance provided?",
      date: "2024-12-14",
      formType: "Homepage Enquiry",
    },
    {
      id: "3",
      name: "Ashley Adams",
      email: "ashley@example.com",
      enquiry: "Pet-friendly tours?",
      date: "2024-12-13",
      formType: "Homepage Enquiry",
    },
    {
      id: "4",
      name: "Matthew Nelson",
      email: "matthew@example.com",
      enquiry: "Wheelchair accessible?",
      date: "2024-12-12",
      formType: "Homepage Enquiry",
    },
    {
      id: "5",
      name: "Rachel King",
      email: "rachel@example.com",
      enquiry: "Group discounts?",
      date: "2024-12-11",
      formType: "Homepage Enquiry",
    },
  ],
  familyPackageNotify: [
    {
      id: "1",
      name: "Jason Carter",
      email: "jason@example.com",
      familyMembers: 4,
      date: "2024-12-15",
      formType: "Family Package",
    },
    {
      id: "2",
      name: "Danielle Mitchell",
      email: "danielle@example.com",
      familyMembers: 5,
      date: "2024-12-14",
      formType: "Family Package",
    },
    {
      id: "3",
      name: "Tyler Roberts",
      email: "tyler@example.com",
      familyMembers: 3,
      date: "2024-12-13",
      formType: "Family Package",
    },
    {
      id: "4",
      name: "Victoria Hayes",
      email: "victoria@example.com",
      familyMembers: 6,
      date: "2024-12-12",
      formType: "Family Package",
    },
  ],
}
